// Generated by gencpp from file robomaker_simulation_msgs/AddTagsRequest.msg
// DO NOT EDIT!


#ifndef ROBOMAKER_SIMULATION_MSGS_MESSAGE_ADDTAGSREQUEST_H
#define ROBOMAKER_SIMULATION_MSGS_MESSAGE_ADDTAGSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robomaker_simulation_msgs/Tag.h>

namespace robomaker_simulation_msgs
{
template <class ContainerAllocator>
struct AddTagsRequest_
{
  typedef AddTagsRequest_<ContainerAllocator> Type;

  AddTagsRequest_()
    : tags()  {
    }
  AddTagsRequest_(const ContainerAllocator& _alloc)
    : tags(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::robomaker_simulation_msgs::Tag_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::robomaker_simulation_msgs::Tag_<ContainerAllocator> >> _tags_type;
  _tags_type tags;





  typedef boost::shared_ptr< ::robomaker_simulation_msgs::AddTagsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robomaker_simulation_msgs::AddTagsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddTagsRequest_

typedef ::robomaker_simulation_msgs::AddTagsRequest_<std::allocator<void> > AddTagsRequest;

typedef boost::shared_ptr< ::robomaker_simulation_msgs::AddTagsRequest > AddTagsRequestPtr;
typedef boost::shared_ptr< ::robomaker_simulation_msgs::AddTagsRequest const> AddTagsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robomaker_simulation_msgs::AddTagsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robomaker_simulation_msgs::AddTagsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robomaker_simulation_msgs::AddTagsRequest_<ContainerAllocator1> & lhs, const ::robomaker_simulation_msgs::AddTagsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.tags == rhs.tags;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robomaker_simulation_msgs::AddTagsRequest_<ContainerAllocator1> & lhs, const ::robomaker_simulation_msgs::AddTagsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robomaker_simulation_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robomaker_simulation_msgs::AddTagsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robomaker_simulation_msgs::AddTagsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robomaker_simulation_msgs::AddTagsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robomaker_simulation_msgs::AddTagsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robomaker_simulation_msgs::AddTagsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robomaker_simulation_msgs::AddTagsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robomaker_simulation_msgs::AddTagsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "33d0d627ff06b11fa5f66485c6bef84d";
  }

  static const char* value(const ::robomaker_simulation_msgs::AddTagsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x33d0d627ff06b11fULL;
  static const uint64_t static_value2 = 0xa5f66485c6bef84dULL;
};

template<class ContainerAllocator>
struct DataType< ::robomaker_simulation_msgs::AddTagsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robomaker_simulation_msgs/AddTagsRequest";
  }

  static const char* value(const ::robomaker_simulation_msgs::AddTagsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robomaker_simulation_msgs::AddTagsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.\n"
"# SPDX-License-Identifier: Apache-2.0\n"
"#\n"
"# This service is loaded at runtime in AWS RoboMaker simulations.\n"
"#\n"
"# Calling this service will set tags on the running simulation\n"
"# job.\n"
"#\n"
"# More information about usage can be found here:\n"
"# https://docs.aws.amazon.com/robomaker\n"
"#\n"
"# This uses the TagResourceAPI:\n"
"# https://docs.aws.amazon.com/robomaker/latest/dg/API_TagResource.html\n"
"\n"
"# List of key:value pairs to set as tags on the simulation job.\n"
"Tag[] tags\n"
"\n"
"================================================================================\n"
"MSG: robomaker_simulation_msgs/Tag\n"
"# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.\n"
"# SPDX-License-Identifier: Apache-2.0\n"
"string key\n"
"string value\n"
;
  }

  static const char* value(const ::robomaker_simulation_msgs::AddTagsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robomaker_simulation_msgs::AddTagsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tags);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTagsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robomaker_simulation_msgs::AddTagsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robomaker_simulation_msgs::AddTagsRequest_<ContainerAllocator>& v)
  {
    s << indent << "tags[]" << std::endl;
    for (size_t i = 0; i < v.tags.size(); ++i)
    {
      s << indent << "  tags[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::robomaker_simulation_msgs::Tag_<ContainerAllocator> >::stream(s, indent + "    ", v.tags[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOMAKER_SIMULATION_MSGS_MESSAGE_ADDTAGSREQUEST_H
