// Generated by gencpp from file robomaker_simulation_msgs/ListTagsResponse.msg
// DO NOT EDIT!


#ifndef ROBOMAKER_SIMULATION_MSGS_MESSAGE_LISTTAGSRESPONSE_H
#define ROBOMAKER_SIMULATION_MSGS_MESSAGE_LISTTAGSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robomaker_simulation_msgs/Tag.h>

namespace robomaker_simulation_msgs
{
template <class ContainerAllocator>
struct ListTagsResponse_
{
  typedef ListTagsResponse_<ContainerAllocator> Type;

  ListTagsResponse_()
    : success(false)
    , message()
    , tags()  {
    }
  ListTagsResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , tags(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef std::vector< ::robomaker_simulation_msgs::Tag_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::robomaker_simulation_msgs::Tag_<ContainerAllocator> >> _tags_type;
  _tags_type tags;





  typedef boost::shared_ptr< ::robomaker_simulation_msgs::ListTagsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robomaker_simulation_msgs::ListTagsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ListTagsResponse_

typedef ::robomaker_simulation_msgs::ListTagsResponse_<std::allocator<void> > ListTagsResponse;

typedef boost::shared_ptr< ::robomaker_simulation_msgs::ListTagsResponse > ListTagsResponsePtr;
typedef boost::shared_ptr< ::robomaker_simulation_msgs::ListTagsResponse const> ListTagsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robomaker_simulation_msgs::ListTagsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robomaker_simulation_msgs::ListTagsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robomaker_simulation_msgs::ListTagsResponse_<ContainerAllocator1> & lhs, const ::robomaker_simulation_msgs::ListTagsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.tags == rhs.tags;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robomaker_simulation_msgs::ListTagsResponse_<ContainerAllocator1> & lhs, const ::robomaker_simulation_msgs::ListTagsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robomaker_simulation_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robomaker_simulation_msgs::ListTagsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robomaker_simulation_msgs::ListTagsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robomaker_simulation_msgs::ListTagsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robomaker_simulation_msgs::ListTagsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robomaker_simulation_msgs::ListTagsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robomaker_simulation_msgs::ListTagsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robomaker_simulation_msgs::ListTagsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f351af60fa94133527414ffdcaacf51b";
  }

  static const char* value(const ::robomaker_simulation_msgs::ListTagsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf351af60fa941335ULL;
  static const uint64_t static_value2 = 0x27414ffdcaacf51bULL;
};

template<class ContainerAllocator>
struct DataType< ::robomaker_simulation_msgs::ListTagsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robomaker_simulation_msgs/ListTagsResponse";
  }

  static const char* value(const ::robomaker_simulation_msgs::ListTagsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robomaker_simulation_msgs::ListTagsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# True if tags were successfully fetched. False otherwise.\n"
"bool success\n"
"\n"
"# Message containing more information about the error if success\n"
"# is false.\n"
"string message\n"
"\n"
"# The tags associated with the simulation provided as\n"
"# key:value pairs.\n"
"Tag[] tags\n"
"\n"
"================================================================================\n"
"MSG: robomaker_simulation_msgs/Tag\n"
"# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.\n"
"# SPDX-License-Identifier: Apache-2.0\n"
"string key\n"
"string value\n"
;
  }

  static const char* value(const ::robomaker_simulation_msgs::ListTagsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robomaker_simulation_msgs::ListTagsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.tags);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ListTagsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robomaker_simulation_msgs::ListTagsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robomaker_simulation_msgs::ListTagsResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "tags[]" << std::endl;
    for (size_t i = 0; i < v.tags.size(); ++i)
    {
      s << indent << "  tags[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::robomaker_simulation_msgs::Tag_<ContainerAllocator> >::stream(s, indent + "    ", v.tags[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOMAKER_SIMULATION_MSGS_MESSAGE_LISTTAGSRESPONSE_H
