// Generated by gencpp from file robomaker_simulation_msgs/ListTagsRequest.msg
// DO NOT EDIT!


#ifndef ROBOMAKER_SIMULATION_MSGS_MESSAGE_LISTTAGSREQUEST_H
#define ROBOMAKER_SIMULATION_MSGS_MESSAGE_LISTTAGSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robomaker_simulation_msgs
{
template <class ContainerAllocator>
struct ListTagsRequest_
{
  typedef ListTagsRequest_<ContainerAllocator> Type;

  ListTagsRequest_()
    {
    }
  ListTagsRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::robomaker_simulation_msgs::ListTagsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robomaker_simulation_msgs::ListTagsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ListTagsRequest_

typedef ::robomaker_simulation_msgs::ListTagsRequest_<std::allocator<void> > ListTagsRequest;

typedef boost::shared_ptr< ::robomaker_simulation_msgs::ListTagsRequest > ListTagsRequestPtr;
typedef boost::shared_ptr< ::robomaker_simulation_msgs::ListTagsRequest const> ListTagsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robomaker_simulation_msgs::ListTagsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robomaker_simulation_msgs::ListTagsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace robomaker_simulation_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robomaker_simulation_msgs::ListTagsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robomaker_simulation_msgs::ListTagsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robomaker_simulation_msgs::ListTagsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robomaker_simulation_msgs::ListTagsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robomaker_simulation_msgs::ListTagsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robomaker_simulation_msgs::ListTagsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robomaker_simulation_msgs::ListTagsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::robomaker_simulation_msgs::ListTagsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::robomaker_simulation_msgs::ListTagsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robomaker_simulation_msgs/ListTagsRequest";
  }

  static const char* value(const ::robomaker_simulation_msgs::ListTagsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robomaker_simulation_msgs::ListTagsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.\n"
"# SPDX-License-Identifier: Apache-2.0\n"
"#\n"
"# This service is loaded at runtime in AWS RoboMaker simulations.\n"
"#\n"
"# Calling this service will set tags on the running simulation\n"
"# job.\n"
"#\n"
"# More information about usage can be found here:\n"
"# https://docs.aws.amazon.com/robomaker\n"
"#\n"
"# This uses the ListTagsForResourceAPI:\n"
"# https://docs.aws.amazon.com/robomaker/latest/dg/API_ListTagsForResource.html\n"
"\n"
;
  }

  static const char* value(const ::robomaker_simulation_msgs::ListTagsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robomaker_simulation_msgs::ListTagsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ListTagsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robomaker_simulation_msgs::ListTagsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::robomaker_simulation_msgs::ListTagsRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROBOMAKER_SIMULATION_MSGS_MESSAGE_LISTTAGSREQUEST_H
