// Generated by gencpp from file robomaker_simulation_msgs/RemoveTagsRequest.msg
// DO NOT EDIT!


#ifndef ROBOMAKER_SIMULATION_MSGS_MESSAGE_REMOVETAGSREQUEST_H
#define ROBOMAKER_SIMULATION_MSGS_MESSAGE_REMOVETAGSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robomaker_simulation_msgs
{
template <class ContainerAllocator>
struct RemoveTagsRequest_
{
  typedef RemoveTagsRequest_<ContainerAllocator> Type;

  RemoveTagsRequest_()
    : keys()  {
    }
  RemoveTagsRequest_(const ContainerAllocator& _alloc)
    : keys(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _keys_type;
  _keys_type keys;





  typedef boost::shared_ptr< ::robomaker_simulation_msgs::RemoveTagsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robomaker_simulation_msgs::RemoveTagsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RemoveTagsRequest_

typedef ::robomaker_simulation_msgs::RemoveTagsRequest_<std::allocator<void> > RemoveTagsRequest;

typedef boost::shared_ptr< ::robomaker_simulation_msgs::RemoveTagsRequest > RemoveTagsRequestPtr;
typedef boost::shared_ptr< ::robomaker_simulation_msgs::RemoveTagsRequest const> RemoveTagsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robomaker_simulation_msgs::RemoveTagsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robomaker_simulation_msgs::RemoveTagsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robomaker_simulation_msgs::RemoveTagsRequest_<ContainerAllocator1> & lhs, const ::robomaker_simulation_msgs::RemoveTagsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.keys == rhs.keys;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robomaker_simulation_msgs::RemoveTagsRequest_<ContainerAllocator1> & lhs, const ::robomaker_simulation_msgs::RemoveTagsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robomaker_simulation_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robomaker_simulation_msgs::RemoveTagsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robomaker_simulation_msgs::RemoveTagsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robomaker_simulation_msgs::RemoveTagsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robomaker_simulation_msgs::RemoveTagsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robomaker_simulation_msgs::RemoveTagsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robomaker_simulation_msgs::RemoveTagsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robomaker_simulation_msgs::RemoveTagsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9bf34c7d40859cce227de2428e93c00a";
  }

  static const char* value(const ::robomaker_simulation_msgs::RemoveTagsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9bf34c7d40859cceULL;
  static const uint64_t static_value2 = 0x227de2428e93c00aULL;
};

template<class ContainerAllocator>
struct DataType< ::robomaker_simulation_msgs::RemoveTagsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robomaker_simulation_msgs/RemoveTagsRequest";
  }

  static const char* value(const ::robomaker_simulation_msgs::RemoveTagsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robomaker_simulation_msgs::RemoveTagsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.\n"
"# SPDX-License-Identifier: Apache-2.0\n"
"#\n"
"# This service is loaded at runtime in AWS RoboMaker simulations.\n"
"#\n"
"# Calling this service will remove tags from the running\n"
"# simulation job.\n"
"#\n"
"# More information about usage can be found here:\n"
"# https://docs.aws.amazon.com/robomaker\n"
"#\n"
"# This uses the UntagResource API:\n"
"# https://docs.aws.amazon.com/robomaker/latest/dg/API_UntagResource.html\n"
"\n"
"# Key values for tags to remove from the simulation job\n"
"string[] keys\n"
;
  }

  static const char* value(const ::robomaker_simulation_msgs::RemoveTagsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robomaker_simulation_msgs::RemoveTagsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.keys);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RemoveTagsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robomaker_simulation_msgs::RemoveTagsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robomaker_simulation_msgs::RemoveTagsRequest_<ContainerAllocator>& v)
  {
    s << indent << "keys[]" << std::endl;
    for (size_t i = 0; i < v.keys.size(); ++i)
    {
      s << indent << "  keys[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.keys[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOMAKER_SIMULATION_MSGS_MESSAGE_REMOVETAGSREQUEST_H
